
server:
  port: 8001
  
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: C##ONO
    password: ONO
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/memberimgs/
      
# jpa config
  jpa:
    generate-ddl: false
    show-sql: true
    database: oracle
    properties:
      hibernate:
        '[format_sql]': true      

  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          
#파일을 저장할 위치와 응답시 파일 주소 설정
file:
  add-resource-locations: classpath:/static/uploadFiles
  add-resource-handler: /uplosdFiles/**
  file-dir: src/main/resources/static/uploadFiles
  file-url: http://localhost:8001/uploadFiles

# 이미지 저장할 위치와 응답 시 이미지 주소 설정
image:
  # WebConfig에 세팅
  add-resource-locations: classpath:/static/memberimgs/
  add-resource-handler: /memberimgs/**
  # ProductService에 세팅
  image-dir: src/main/resources/static/memberimgs
  image-url: http://localhost:8001/memberimgs/

# HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
# Secret 값은 특정 문자열을 Base64 로 인코딩한 값 사용
jwt:
  secret: 
